config/routes.rb
TenApp::Application.routes.draw do
  # devise_for :users
  root to: "news#index"
  # devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :admin_users, {class_name: 'User'}.merge(ActiveAdmin::Devise.config)
  devise_for :users, :controllers => { registrations: 'registrations' }
  ActiveAdmin.routes(self)
  resources :news
  resources :article
  resources :account do
    resources :images
  end
  get '/set_images/', :to => 'article#set_images', as: 'set_images'
  post '/get_images/', :to => 'images#get_images', as: 'get_images'
  # get 'account/:id', to: 'pages#account', as: 'account'
  # get 'accounts', to: 'pages#accounts'
  # post '/account/:id/images', to: 'images#create', as: 'save'

end

app/models/active_admin_adapter.rb
class ActiveAdminAdapter < ActiveAdmin::AuthorizationAdapter

  def authorized?(action, subject = nil)
    if user.admin != true
      return true
    end
    true
  end

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :images, as: :imageable, dependent: :destroy
  accepts_nested_attributes_for :images, reject_if: proc { |attributes| attributes['file'].blank? }, allow_destroy: true

  enum theme: { IT_technology: 0, Adventure: 1, Family: 2, Other: 3 }
end

app/models/image.rb
class Image < ApplicationRecord
  mount_uploader :file, ImageUploader
  belongs_to :imageable, polymorphic: true
end

app/models/news_category.rb
class NewsCategory < ApplicationRecord
end

app/models/news_item.rb
class NewsItem < ApplicationRecord
  mount_uploader :cover, CoverUploader
  has_many :images, as: :imageable, dependent: :destroy
  accepts_nested_attributes_for :images, reject_if: proc { |attributes| attributes['file'].blank? }, allow_destroy: true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :images, as: :imageable, dependent: :destroy
end

app/controllers/account_controller.rb
class AccountController < InheritedResources::Base

def index
  @users = User.all
end

def show
  @user = User.find(params[:id])
  @images = @user.images
  @my_test_var = 'Iam'
end

private

def account_params
  params.require(:pages).permit(:id)
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  protect_from_forgery with: :exception

  before_action :set_locale

   def set_locale
     I18n.locale = (session[:locale] || params[:locale] || extract_locale_from_accept_language_header).to_s.downcase.presence || I18n.default_locale
   end

   protected

   def active_access_denied(exception)
     redirect_to root_path, alert: exception.message
   end

  private


    def extract_locale_from_accept_language_header
      request.env['HTTP_ACCEPT_LANGUAGE'].scan(/^[a-z]{2}/).first
    end
end

app/controllers/article_controller.rb
class ArticleController < InheritedResources::Base
before_action :authenticate_user!, except: [:index]

def index
  @articles = Article.all
  print @articles 
  @user = User.find(current_user.id)
end

def show
  @article = Article.find(params[:id])
end

private

  def news_item_params
    params.require(:news_item).permit(:id, :title, :body, :theme)
  end

end

app/controllers/images_controller.rb
class ImagesController < InheritedResources::Base
before_action :authenticate_user!, except: [:index]
before_action :load_imageable, only: [:create]

  def create

      # @image = Image.new(image_params)
      @image = @imageable.images.build(image_params)
      if @image.save
        redirect_to request.referrer, notice: 'The image successfully saved.'
      else
        redirect_to request.referrer, notice: 'The image did not save.'
      end
  end

  private

    def image_params
      params.require(:image).permit(:file)
    end

    def load_imageable
    resource, id = request.path.split('/')[1,2]
    if resource == "account"
      @imageable = User.find(id)
    else
      @imageable = resource.singularize.classify.constantize.find(id)
    end

  end

end

app/controllers/news_controller.rb
class NewsController < InheritedResources::Base
before_action :authenticate_user!

def index
  @news = NewsItem.all
end

  private

    def news_item_params
      params.require(:news_item).permit(:title, :cover, :news_category, :body)
    end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/news_items_helper.rb
module NewsItemsHelper
end

app/views/article/_article_panel.html.slim
.details
  span
    h4
      'Название: &nbsp;
    strong
      = article.title
  span
    h4
      'Автор: &nbsp;
    strong
      - if article.user_id
        = article.user_id
      - else
        'Noname
  span
    h4
      'Тема: &nbsp;
    strong
      = article.theme
  span
    h4
      'Дата написания: &nbsp;
    strong
      = article.created_at

app/views/article/index.html.slim
span.topic
  'Статьи пользователей
.article_block.content-margin
  - @articles.each_with_index do |item, i|
    .article_index.article
      - if item.body.blank? || item.title.blank?
        - next
      h3
        = item.title
      br
        = truncate(item.body, length: 1000)
        br
        = link_to I18n.t('activerecord.attributes.article.more'), article_path(item.id)

app/views/article/new.html.slim
br
= form_with(model: @article, url: '/article') do |form|
  .field
    = form.label :title
    br
    = form.text_field :title
  br
  .field
    = form.label :body
    br
    = form.text_area :body, size: "10x15", required: true
  br
  .field
    = form.label :theme
    br
    = form.text_field :theme
  br
  - @article.images.each do |u|
    .img-show
      = image_tag u.url(:thumb)
      = link_to "Удалить", delete_picture_path(article.id, article.pictures.index(u)), method: :get
  br
  .field
    = form.file_field :pictures, multiple: true
  = form.hidden_field :user_id, :value => current_user.id
  br
  .actions
    = form.submit I18n.t('activerecord.models.article.submit')

app/views/article/set_images.html.slim
#common_block.clearfix
#download_image_block
  form#form_block action="/get_images/" method="POST" enctype="multipart/form-data"
    input type="hidden" name="authenticity_token" value="token_value"
    input type="hidden" name="image_article[article_id]" value="1"
    br
    input.sub type="submit" value="Submit"

app/views/article/show.html.slim
= render 'article_panel', article: @article
.article_show.article.content-margin
  = @article.body

app/views/layouts/application.html.slim
doctype html
html
  head
    title #{TenApp}
    = Gon::Base.render_data
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  body
    = render partial: 'shared/header', locals: {user:@user}
    span class="notice"
      = notice
    span class="alert"
      = alert
    .content
      = yield
    = render 'shared/footer'

app/views/news/index.html.slim
.news_block.clearfix
  - @news.each do |item|
    = item.title
    = image_tag item.cover.url(:thumb) if item.cover?
    = item.body

app/views/pages/accounts.html.slim
@users.each do |user|
  .name
    = user.name
  .email
    = user.email

app/views/shared/_footer.html.slim
footer.footer
   ' Созданно NikMarcos

app/views/shared/_header.html.slim
.navbar
  .search_input
    'Поиск
    input type="text"
  .menu
    - if user_signed_in?
      = link_to I18n.t('activerecord.models.article.other'), article_index_path
    = link_to "Link2", news_index_path
    = link_to "Link3", news_index_path
    = link_to I18n.t('activerecord.models.news_item.other'), news_index_path
    - if user_signed_in?
      span.link1 #{current_user.name}
    - else
      = link_to "", new_user_session_path, method: :get, class:"login-icon"
      = link_to "Зарегестрироваться", new_user_registration_path, method: :get
    - if user_signed_in?
      .acc_menu
        = link_to "Мой аккаунт", account_path(current_user.id), method: :get
        br
        = link_to "Редактировать аккаунт", edit_user_registration_path, method: :get
        br
        .logout
          = link_to "", destroy_user_session_path, class:"logout-icon", method: :delete
  .gumb
    div
    div
    div